---
title: "Định Giá Tài Sản Tài Chính 1"
author: "Nhóm 6"
date: "2024-10-22"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r}
# Load các file data
# 15 mã đầu: Ngành Bất Động Sản (Real Estate)
# 15 mã tiếp theo: Ngành Công Nghiệp (Industry)
# 15 mã cuối: Ngành Tài Chính (Finance)
library(readxl)
closing_price = read_excel("D:/Financial Asset Pricing/closing_price.xlsx", 
    col_types = c("date", rep("numeric", 45)))
#Đơn vị: nghìn VND
colnames(closing_price)[1] = "Date"
head(closing_price, 5)
```
```{r}
market_cap = read_excel("D:/Financial Asset Pricing/market_cap.xlsx", 
    col_types = c("date", rep("numeric", 45)))
#Đơn vị: Tỷ VNĐ
head(market_cap, 5)
```

```{r}
#Tính chuỗi lợi suất của từng cổ phiếu
rate_of_return = log(closing_price[2:229, 2:46]/closing_price[1:228, 2:46])
rate_of_return
```
```{r}
#Tính lợi suất kì vọng
expected_r = colMeans(rate_of_return)
#Tính phương sai, độ lệch chuẩn của lợi suất
var_r = apply(rate_of_return, 2, var)
sigma_r = sqrt(var_r)
stock = cbind(expected_r, sigma_r)
stock
```
```{r}
library(ggplot2)
#Vẽ đồ thị lợi suất 
ror_df=data.frame(closing_price[-1,1],rate_of_return)
for (i in 1:45) {
  rate_of_return_plot <- ggplot(ror_df, aes(x = as.Date(ror_df$Date), y = ror_df[,i+1])) + 
    geom_line(color = "purple", size = 1) + 
    geom_point(color = "red", size = 1)+ 
    geom_hline(yintercept = expected_r[i],color = "black", size=1)+
    labs(title=colnames(ror_df)[i+1],x="Date",y="Rate of return")
  print(rate_of_return_plot)
}
```

```{r}
#TÍNH CÁC CHỈ SỐ NGÀNH
#PHƯƠNG PHÁP 1: PRICE-WEIGHTED AVERAGE
closing_price_data = closing_price[, -1]
#Tính tổng các giá cổ phiếu của từng ngành theo ngày
price_sum = data.frame(matrix(0, nrow = 229, ncol = 3))
for (i in 0:2) {
  price_sum[,i+1] = rowSums(closing_price_data[, (15*i+1):(15*(i+1))])
}
head(price_sum, 5)
```
```{r}
#Tính ma trận split
#Tạo ma trận split ban đầu với tất cả phần tử = 1
split = data.frame(matrix(1, nrow = 229, ncol = 45))
#Viết hàm để đưa các hệ số tách (split ratio) vào trong ma trận split
func = function(date, stock, split_ratio){
i = which(closing_price$Date == as.POSIXct(date, tz = "UTC"))
j = which(names(closing_price) == stock)
split[i, j-1] <<- split_ratio
}
func("2024-07-25", "VPI", 1.2)
func("2024-07-10", "SIP", 1.15)
func("2024-06-24", "HDG", 1.1)
func("2024-07-19", "HHV", 1.05)
func("2023-11-22", "PC1", 1.15)
func("2024-04-11", "PVT", 1.1)
func("2024-09-23", "TMS", 1.07)
func("2024-08-01", "BCG", 1.1)
func("2024-06-14", "VCG", 1.12)
func("2024-06-21", "HAH", 1.15)
func("2023-11-28", "BID", 1.1269)
func("2023-11-30", "CTG", 1.117415)
func("2024-06-20", "TCB", 2)
func("2024-05-31", "ACB", 1.15)
func("2024-08-22", "VIB", 1.17)
colnames(split) = colnames(closing_price_data)
```

```{r}
#Tính ma trận d: Ma trận chứa các ước số d
#Tạo ma trận d ban đầu với tất cả phần tử = 15 vì số mã cổ phiếu của 1 ngành là 15
d = data.frame(matrix(15, nrow = 229, ncol = 3))
for(j in 0:2){
  for(i in 2:229){
    if(any(split[i, (15*j+1):(15*(j+1))]>1)){
      d[i, j+1] = price_sum[i, j+1]*d[i-1, j+1]/sum(closing_price_data[i, (15*j+1):(15*(j+1))]*split[i, (15*j+1):(15*(j+1))])
    }else{d[i, j+1] = d[i-1, j+1]}
  }
}
colnames(d) = c("Real Estate", "Industry", "Finance")
head(d, 30)
```
```{r}
#Tính AP (Average Price)
AP = price_sum/d
#Tạo ma trận AP_0 là vector AP tại thời điểm ban đầu được lặp lại 229 lần
AP_0 = as.data.frame(matrix(rep(as.numeric(AP[1, ]), times = 229), nrow = 229, byrow = TRUE))
#Tính chỉ số
I_1 = 100*AP/AP_0
colnames(I_1) = c("Real Estate", "Industry", "Finance")
I_1
```

```{r}
#PHƯƠNG PHÁP 2: MARKET-VALUE-WEIGHTED INDEX
#Tính tổng vốn hóa thị trường của từng ngành theo ngày
market_cap_data = market_cap[,-1]
total_market_cap = data.frame(matrix(0, nrow = 229, ncol = 3))
for (i in 0:2) {
  total_market_cap[,i+1] = rowSums(market_cap_data[, (15*i+1):(15*(i+1))])
}
colnames(total_market_cap) = c("Real Estate", "Industry", "Finance")
head(total_market_cap, 5)
```


```{r}
#Tính chỉ số
I_2 = data.frame(matrix(0, nrow = 229, ncol = 3))
#Tạo ma trận total_market_cap_0 là vốn hóa thị trường của từng ngành tại thời điểm ban đầu, được lặp lại 229 lần
total_market_cap_0 = as.data.frame(matrix(rep(as.numeric(total_market_cap[1, ]), times = 229), nrow = 229, byrow = TRUE))
I_2 = 100*total_market_cap/total_market_cap_0
colnames(I_2) = c("Real Estate", "Industry", "Finance")
I_2
```

```{r}
#PHƯƠNG PHÁP 3: EQUALLY-WEIGHTED INDEX
#Tính PI
PI = data.frame(matrix(0, nrow = 228, ncol = 3))
for (i in 0:2) {
PI[, i+1] = rowMeans(closing_price_data[2:229, (15*i+1):(15*(i+1))]/closing_price_data[1:228, (15*i+1):(15*(i+1))])
}
colnames(PI) = c("Real Estate", "Industry", "Finance")
head(PI, 5)
```
```{r}
#Tính chỉ số
I_3 = data.frame(matrix(0, nrow = 228, ncol = 3))
I_3 = rbind(c(rep(100, 3)), I_3) #Các phần tử ở dòng 1 bằng 100
for(j in 1:3){
 for (i in 2:229){
  I_3[i, j] = I_3[i - 1, j]*PI[i - 1, j]
 }
}
colnames(I_3) = c("Real Estate", "Industry", "Finance")
I_3
```

```{r}
#TỔNG HỢP CÁC CHỈ SỐ 
combined_df=data.frame(closing_price[,1],I_1,I_2,I_3)
colnames(combined_df)=c("Date","Real Estate 1","Industry 1","Finance 1","Real Estate 2","Industry 2","Finance 2","Real Estate 3","Industry 3","Finance 3")
head(combined_df, 5)
```

```{r}
#Vẽ đồ thị các ngành theo từng chỉ số 
index_name=c("Price Weighting","Value Weighting","Equal Weighting")

for(j in 1:3){
  index_plot <- ggplot(data = combined_df, aes(x = as.Date(combined_df[, 1])))+
    geom_line(aes(y = combined_df[, 3*j-1], color = "Real Estate"), size = 1) +  
    geom_line(aes(y = combined_df[, 3*j], color = "Industry"), size = 1) +  
    geom_line(aes(y = combined_df[, 3*j+1], color = "Finance"), size = 1) + 
    labs(title = index_name[j], x = "Date", y = "Index") +
    scale_color_manual(values=c("Real Estate" = "red","Industry" = "blue","Finance" = "green")) +  
    theme(legend.title = element_blank())

  print(index_plot)
}
```

```{r}
# Vẽ đồ thị các chỉ số theo từng ngành 
nganh=c("Real Estate","Industry","Finance")

for(j in 1:3){
  nganh_plot <- ggplot(data = combined_df, aes(x = as.Date(combined_df[, 1])))+
    geom_line(aes(y = combined_df[, j+1], color = "Price-Weighted Average"), size = 1) +  
    geom_line(aes(y = combined_df[, j+4], color = "Market-Value-Weighted Index"), size = 1) +  
    geom_line(aes(y = combined_df[, j+7], color = "Equally-Weighted Index"), size = 1) + 
    labs(title = nganh[j], x = "Date", y = "Index") +
    scale_color_manual(values=c("Price-Weighted Average" = "red","Market-Value-Weighted Index" = "blue","Equally-Weighted Index" = "green")) +  
    theme(legend.title = element_blank())

  print(nganh_plot)
}
```

